/**
 * This class is generated by jOOQ
 */
package com.metapx.server.data_model.jooq;


import com.metapx.server.data_model.jooq.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = com.metapx.server.data_model.jooq.tables.Users.USERS;
}
